spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
    username: root
    password: lorcx
  jpa:
    hibernate:
      ddl-auto: update # 第一次启动创建表，如果有数据则不动
      # ddl-auto: create # 每次启动都会自动创建表
    show-sql: true